# Generated by Django 6.0.3 on 2026-03-23 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=120, verbose_name='Familiya')),
                ('phone_number', models.CharField(help_text='Masalan: +998 90 123 45 67', max_length=32, validators=[django.core.validators.RegexValidator(message="Telefon formatini to'g'ri kiriting.", regex='^[\\d\\+\\-\\(\\)\\s]+$')], verbose_name='Telefon raqami')),
                ('asset_type', models.CharField(choices=[('car', 'Mashina'), ('phone', 'Telefon'), ('passport', 'Passport'), ('document', 'Hujjat'), ('other', 'Boshqa')], default='car', max_length=20, verbose_name='Buyum turi')),
                ('asset_label', models.CharField(help_text='Mashina nomeri, telefon modeli, passport seriyasi va hokazo.', max_length=180, verbose_name='Identifikator')),
                ('qr_code', models.SlugField(blank=True, help_text="QR link ichida ishlatiladigan noyob kod. Bo'sh qoldirilsa avtomatik yaratiladi.", max_length=80, unique=True, verbose_name='QR kodi')),
                ('note', models.TextField(blank=True, help_text="Topib olgan odam ko'rishi kerak bo'lgan qisqa izoh.", verbose_name="Qo'shimcha izoh")),
                ('is_active', models.BooleanField(default=True, help_text="Faollik o'chirilsa public sahifa ishlamaydi.", verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'QR kontakt',
                'verbose_name_plural': 'QR kontaktlar',
                'ordering': ['-updated_at'],
            },
        ),
    ]
