# Generated by Django 6.0.3 on 2026-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhub', '0002_assetcontact_public_code_alter_assetcontact_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('qr_image', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='QR rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'QR Kod',
                'verbose_name_plural': 'QR Kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AssetContact',
        ),
    ]
