# Generated by Django 6.0.3 on 2026-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhub', '0003_qrcode_delete_assetcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Rasmi'),
        ),
    ]
